import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Info, Loader2, X } from 'lucide-react';

import { createTeacherSchema } from '@/schemas/teacher.schema';
import type { CreateTeacherFormValues } from '@/schemas/teacher.schema';
import { useCreateTeacher } from '@/hooks/useTeachers';

interface TeacherModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function TeacherModal({ isOpen, onClose }: TeacherModalProps) {
  const { mutate: createTeacher, isPending } = useCreateTeacher();

  const { register, handleSubmit, formState: { errors }, reset } = useForm<CreateTeacherFormValues>({
    resolver: zodResolver(createTeacherSchema),
  });

  if (!isOpen) return null;

  const onSubmit = (data: CreateTeacherFormValues) => {
    createTeacher(data, {
      onSuccess: () => {
        reset(); 
        onClose(); 
      }
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-gray-900/60 backdrop-blur-sm p-4">
      <div className="relative w-full max-w-2xl rounded-2xl bg-white shadow-2xl animate-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-gray-100 p-6 bg-gray-50/50 rounded-t-2xl">
          <div>
            <h3 className="text-xl font-black text-gray-900 tracking-tight">Onboard New Teacher</h3>
            <p className="text-sm font-medium text-gray-500 mt-1">Create a new staff account and profile.</p>
          </div>
          <button onClick={onClose} className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-200 rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-primary-500">
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Form Body */}
        <div className="p-6">
          <div className="mb-8 flex items-start rounded-xl bg-blue-50 p-4 text-sm font-medium text-blue-800 border border-blue-100">
            <Info className="mr-3 h-5 w-5 flex-shrink-0 mt-0.5" />
            <p><strong>Note:</strong> Employee numbers are automatically generated by the system upon successful onboarding.</p>
          </div>

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-8">
            
            {/* Section 1: User Identity */}
            <div>
              <h4 className="mb-4 text-[10px] font-black text-gray-400 uppercase tracking-widest border-b border-gray-100 pb-2">Login & Identity</h4>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                <div>
                  <label className="mb-2 block text-sm font-bold text-gray-700">First Name <span className="text-red-500">*</span></label>
                  <input 
                    {...register('first_name')} 
                    aria-invalid={!!errors.first_name}
                    className={`block w-full rounded-xl border ${errors.first_name ? 'border-red-500 ring-1 ring-red-500' : 'border-gray-200'} bg-gray-50 p-3 text-sm font-medium text-gray-900 focus:border-primary-500 focus:ring-2 focus:ring-primary-500 outline-none transition-all`} 
                  />
                  {errors.first_name && <p className="mt-1.5 text-xs font-semibold text-red-500">{errors.first_name.message}</p>}
                </div>
                <div>
                  <label className="mb-2 block text-sm font-bold text-gray-700">Last Name <span className="text-red-500">*</span></label>
                  <input 
                    {...register('last_name')} 
                    aria-invalid={!!errors.last_name}
                    className={`block w-full rounded-xl border ${errors.last_name ? 'border-red-500 ring-1 ring-red-500' : 'border-gray-200'} bg-gray-50 p-3 text-sm font-medium text-gray-900 focus:border-primary-500 focus:ring-2 focus:ring-primary-500 outline-none transition-all`} 
                  />
                  {errors.last_name && <p className="mt-1.5 text-xs font-semibold text-red-500">{errors.last_name.message}</p>}
                </div>
                <div>
                  <label className="mb-2 block text-sm font-bold text-gray-700">Email Address <span className="text-red-500">*</span></label>
                  <input 
                    {...register('email')} 
                    type="email" 
                    aria-invalid={!!errors.email}
                    className={`block w-full rounded-xl border ${errors.email ? 'border-red-500 ring-1 ring-red-500' : 'border-gray-200'} bg-gray-50 p-3 text-sm font-medium text-gray-900 focus:border-primary-500 focus:ring-2 focus:ring-primary-500 outline-none transition-all`} 
                  />
                  {errors.email && <p className="mt-1.5 text-xs font-semibold text-red-500">{errors.email.message}</p>}
                </div>
                <div>
                  <label className="mb-2 block text-sm font-bold text-gray-700">Temporary Password <span className="text-red-500">*</span></label>
                  <input 
                    {...register('password')} 
                    type="password" 
                    aria-invalid={!!errors.password}
                    className={`block w-full rounded-xl border ${errors.password ? 'border-red-500 ring-1 ring-red-500' : 'border-gray-200'} bg-gray-50 p-3 text-sm font-medium text-gray-900 focus:border-primary-500 focus:ring-2 focus:ring-primary-500 outline-none transition-all`} 
                  />
                  {errors.password && <p className="mt-1.5 text-xs font-semibold text-red-500">{errors.password.message}</p>}
                </div>
              </div>
            </div>

            {/* Section 2: Professional Profile */}
            <div>
              <h4 className="mb-4 text-[10px] font-black text-gray-400 uppercase tracking-widest border-b border-gray-100 pb-2">Professional Profile</h4>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                <div>
                  <label className="mb-2 block text-sm font-bold text-gray-700">Qualification</label>
                  <input 
                    {...register('qualification')} 
                    placeholder="e.g. BSc Education" 
                    className="block w-full rounded-xl border border-gray-200 bg-gray-50 p-3 text-sm font-medium text-gray-900 focus:border-primary-500 focus:ring-2 focus:ring-primary-500 outline-none transition-all placeholder:text-gray-400" 
                  />
                </div>
                <div>
                  <label className="mb-2 block text-sm font-bold text-gray-700">Specialization</label>
                  <input 
                    {...register('specialization')} 
                    placeholder="e.g. Mathematics & Physics" 
                    className="block w-full rounded-xl border border-gray-200 bg-gray-50 p-3 text-sm font-medium text-gray-900 focus:border-primary-500 focus:ring-2 focus:ring-primary-500 outline-none transition-all placeholder:text-gray-400" 
                  />
                </div>
              </div>
            </div>

            {/* Actions */}
            <div className="flex items-center justify-end space-x-3 rounded-b border-t border-gray-100 pt-6 mt-8">
              <button type="button" onClick={onClose} className="px-5 py-2.5 text-sm font-bold text-gray-700 hover:bg-gray-100 rounded-xl transition-colors focus:outline-none focus:ring-2 focus:ring-gray-200">
                Cancel
              </button>
              <button type="submit" disabled={isPending} className="flex items-center justify-center min-w-[140px] rounded-xl bg-primary-600 px-6 py-2.5 text-sm font-bold text-white shadow-lg shadow-primary-200 hover:bg-primary-700 disabled:opacity-50 transition-all active:scale-95 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2">
                {isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Add Teacher
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}