import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Info, Loader2, X } from 'lucide-react';

import { createTeacherSchema } from '@/schemas/teacher.schema';
import type { CreateTeacherFormValues } from '@/schemas/teacher.schema';
import { useCreateTeacher } from '@/hooks/useTeachers';

interface TeacherModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function TeacherModal({ isOpen, onClose }: TeacherModalProps) {
  const { mutate: createTeacher, isPending } = useCreateTeacher();

  const { register, handleSubmit, formState: { errors }, reset } = useForm<CreateTeacherFormValues>({
    resolver: zodResolver(createTeacherSchema),
  });

  if (!isOpen) return null;

  const onSubmit = (data: CreateTeacherFormValues) => {
    createTeacher(data, {
      onSuccess: () => {
        reset(); 
        onClose(); 
      }
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-gray-900/60 backdrop-blur-sm p-4">
      <div className="relative w-full max-w-2xl rounded-lg bg-white shadow-xl">
        
        {/* Header */}
        <div className="flex items-center justify-between rounded-t border-b p-4">
          <h3 className="text-xl font-semibold text-gray-900">Onboard New Teacher</h3>
          <button onClick={onClose} className="rounded-lg bg-transparent p-1.5 text-sm text-gray-400 hover:bg-gray-200 hover:text-gray-900">
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Form Body */}
        <div className="p-6">
          <div className="mb-6 flex items-start rounded-lg bg-blue-50 p-4 text-sm text-blue-800 border border-blue-100">
            <Info className="mr-3 h-5 w-5 flex-shrink-0 mt-0.5" />
            <p><strong>Note:</strong> Employee numbers are automatically generated by the system upon successful onboarding.</p>
          </div>

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
            
            {/* Section 1: User Identity */}
            <div>
              <h4 className="mb-4 text-sm font-medium text-gray-500 uppercase tracking-wider">Login & Identity</h4>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="mb-2 block text-sm font-medium text-gray-900">First Name <span className="text-red-500">*</span></label>
                  <input {...register('first_name')} className={`block w-full rounded-lg border ${errors.first_name ? 'border-red-500' : 'border-gray-300'} bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-primary-500 focus:ring-primary-500`} />
                  {errors.first_name && <p className="mt-1 text-xs text-red-500">{errors.first_name.message}</p>}
                </div>
                <div>
                  <label className="mb-2 block text-sm font-medium text-gray-900">Last Name <span className="text-red-500">*</span></label>
                  <input {...register('last_name')} className={`block w-full rounded-lg border ${errors.last_name ? 'border-red-500' : 'border-gray-300'} bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-primary-500 focus:ring-primary-500`} />
                  {errors.last_name && <p className="mt-1 text-xs text-red-500">{errors.last_name.message}</p>}
                </div>
                <div>
                  <label className="mb-2 block text-sm font-medium text-gray-900">Email Address <span className="text-red-500">*</span></label>
                  <input {...register('email')} type="email" className={`block w-full rounded-lg border ${errors.email ? 'border-red-500' : 'border-gray-300'} bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-primary-500 focus:ring-primary-500`} />
                  {errors.email && <p className="mt-1 text-xs text-red-500">{errors.email.message}</p>}
                </div>
                <div>
                  <label className="mb-2 block text-sm font-medium text-gray-900">Temporary Password <span className="text-red-500">*</span></label>
                  <input {...register('password')} type="password" className={`block w-full rounded-lg border ${errors.password ? 'border-red-500' : 'border-gray-300'} bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-primary-500 focus:ring-primary-500`} />
                  {errors.password && <p className="mt-1 text-xs text-red-500">{errors.password.message}</p>}
                </div>
              </div>
            </div>

            <hr className="border-gray-200" />

            {/* Section 2: Professional Profile */}
            <div>
              <h4 className="mb-4 text-sm font-medium text-gray-500 uppercase tracking-wider">Professional Profile</h4>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="mb-2 block text-sm font-medium text-gray-900">Qualification</label>
                  <input {...register('qualification')} placeholder="e.g. BSc Education" className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-primary-500 focus:ring-primary-500" />
                </div>
                <div>
                  <label className="mb-2 block text-sm font-medium text-gray-900">Specialization</label>
                  <input {...register('specialization')} placeholder="e.g. Mathematics & Physics" className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-primary-500 focus:ring-primary-500" />
                </div>
              </div>
            </div>

            {/* Actions */}
            <div className="flex items-center justify-end space-x-3 rounded-b border-t pt-4">
              <button type="button" onClick={onClose} className="rounded-lg border border-gray-200 bg-white px-5 py-2.5 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-900">
                Cancel
              </button>
              <button type="submit" disabled={isPending} className="flex items-center rounded-lg bg-primary-600 px-5 py-2.5 text-sm font-medium text-white hover:bg-primary-700 disabled:opacity-50">
                {isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Add Teacher
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}