import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Loader2, X, Info } from 'lucide-react';

import { createStudentSchema } from '@/schemas/student.schema';
import type { CreateStudentFormValues } from '@/schemas/student.schema';
import { useCreateStudent } from '@/hooks/useStudents';
import { useClasses } from '@/hooks/useClasses';

interface StudentModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function StudentModal({ isOpen, onClose }: StudentModalProps) {
  const { mutate: createStudent, isPending } = useCreateStudent();
  const { data: classesData, isLoading: isLoadingClasses } = useClasses();

  const { register, handleSubmit, formState: { errors }, reset } = useForm<CreateStudentFormValues>({
    resolver: zodResolver(createStudentSchema),
    defaultValues: {
      first_name: '',
      last_name: '',
      email: '',
      password: '',
      class_id: '',
      date_of_birth: '',
    }
  });

  if (!isOpen) return null;

  const onSubmit = (data: CreateStudentFormValues) => {
    createStudent(data, {
      onSuccess: () => {
        reset(); 
        onClose(); 
      }
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-gray-900/60 backdrop-blur-sm p-4">
      <div className="relative w-full max-w-2xl rounded-xl bg-white shadow-2xl my-8">
        
        <div className="flex items-center justify-between border-b border-gray-100 p-5">
          <h3 className="text-lg font-bold text-gray-900">Admit New Student</h3>
          <button onClick={onClose} className="rounded-full p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-600 transition-colors">
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="p-6 max-h-[75vh] overflow-y-auto">
          
          <div className="mb-6 flex items-start rounded-lg bg-blue-50 p-4 text-sm text-blue-800 border border-blue-100">
            <Info className="mr-3 h-5 w-5 flex-shrink-0 mt-0.5" />
            <p><strong>Note:</strong> Admission numbers are automatically generated by the system. You can securely link Parent/Guardian accounts to this student via the Parent Directory module.</p>
          </div>

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
            
            {/* Section 1: User Identity */}
            <div>
              <h4 className="mb-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Student Login & Identity</h4>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-gray-700">First Name <span className="text-red-500">*</span></label>
                  <input {...register('first_name')} className="block w-full rounded-lg border-gray-300 bg-gray-50 p-2.5 text-sm shadow-sm focus:border-primary-500 focus:ring-primary-500" />
                  {errors.first_name && <p className="mt-1 text-xs text-red-500">{errors.first_name.message}</p>}
                </div>
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-gray-700">Last Name <span className="text-red-500">*</span></label>
                  <input {...register('last_name')} className="block w-full rounded-lg border-gray-300 bg-gray-50 p-2.5 text-sm shadow-sm focus:border-primary-500 focus:ring-primary-500" />
                  {errors.last_name && <p className="mt-1 text-xs text-red-500">{errors.last_name.message}</p>}
                </div>
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-gray-700">Email Address <span className="text-red-500">*</span></label>
                  <input type="email" {...register('email')} className="block w-full rounded-lg border-gray-300 bg-gray-50 p-2.5 text-sm shadow-sm focus:border-primary-500 focus:ring-primary-500" />
                  {errors.email && <p className="mt-1 text-xs text-red-500">{errors.email.message}</p>}
                </div>
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-gray-700">Temporary Password <span className="text-red-500">*</span></label>
                  <input type="password" {...register('password')} className="block w-full rounded-lg border-gray-300 bg-gray-50 p-2.5 text-sm shadow-sm focus:border-primary-500 focus:ring-primary-500" />
                  {errors.password && <p className="mt-1 text-xs text-red-500">{errors.password.message}</p>}
                </div>
              </div>
            </div>

            <hr className="border-gray-100" />

            {/* Section 2: Academic Profile */}
            <div>
              <h4 className="mb-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Academic Details</h4>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-gray-700">Assign to Class <span className="text-red-500">*</span></label>
                  <select {...register('class_id')} className="block w-full rounded-lg border-gray-300 bg-gray-50 p-2.5 text-sm shadow-sm focus:border-primary-500 focus:ring-primary-500" disabled={isLoadingClasses}>
                    <option value="">-- Select a Class --</option>
                    {classesData?.map((cls) => (
                      <option key={cls.id} value={cls.id}>
                        {cls.name} {cls.stream || ''}
                      </option>
                    ))}
                  </select>
                  {errors.class_id && <p className="mt-1 text-xs text-red-500">{errors.class_id.message}</p>}
                </div>
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-gray-700">Date of Birth</label>
                  <input type="date" {...register('date_of_birth')} className="block w-full rounded-lg border-gray-300 bg-gray-50 p-2.5 text-sm shadow-sm focus:border-primary-500 focus:ring-primary-500" />
                </div>
              </div>
            </div>

            {/* Actions */}
            <div className="flex justify-end space-x-3 border-t border-gray-100 pt-5 mt-6">
              <button type="button" onClick={onClose} className="rounded-lg border border-gray-300 bg-white px-5 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 shadow-sm transition-colors">
                Cancel
              </button>
              <button type="submit" disabled={isPending} className="flex rounded-lg bg-primary-600 px-5 py-2 text-sm font-bold text-white hover:bg-primary-700 disabled:opacity-50 shadow-sm shadow-primary-200 transition-colors">
                {isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Admit Student
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}